name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  packages: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert Repo owner to lowercase for docker compatibility
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$OWNER/gns3:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/$OWNER/gns3:latest