name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  packages: write
  contents: read
jobs:
  build:
    environment: 
      name: Github Packages
      url: https://ghcr.io/justingrote/gns3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert Repo owner to lowercase for docker compatibility
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.OWNER }}/gns3:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max